### PR TITLE
Added Course By IITKGP On Blockchain Architecture

### PR DESCRIPTION
**Pull request by llk23r**
It's the most systematic, thorough and technical-concept oriented course on blockchain.

### CODE REVIEW

**Comment by fvictorio** [comment]
Most of the videos in that playlist are not publicly available.

**Comment by llk23r** [comment]
The link now points to the course page instead of the playlist.

**Comment by fvictorio** [comment]
Is this course paid or it just needs registration?

**Comment by pablofullana** [comment]
Link is broken

**Pull request closed without merging**
